language: python
python:
  - "2.7"
  - "pypy"
before_install:
  - sudo apt-get install gnupg
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage coveralls nose --use-mirrors
script:
  - "python setup.py install"
  - "nosetests tests --with-coverage --cover-package=mailpile"
after_success:
  - "coveralls"

